In [2]:
# Import library yang diperlukan
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

# Membuat dataframe dari tabel yang diberikan
data = pd.DataFrame({
    'Usia': ['55 Ke atas', '55 Kurang dari', '55 Ke atas', '55 Kurang dari', '55 Ke atas', '55 Ke atas', 
             '55 Kurang dari', '55 Ke atas', '55 Kurang dari', '55 Ke atas', '55 Kurang dari', '55 Kurang dari', 
             '55 Kurang dari', '55 Ke atas'],
    'Status bangunan tempat tinggal': ['Tidak', 'Sendiri', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 
                                       'Sendiri', 'Tidak', 'Sendiri', 'Sendiri', 'Sendiri', 'Tidak'],
    'Pekerjaan': ['Tidak', 'Bekerja', 'Tidak', 'Bekerja', 'Tidak', 'Tidak', 'Bekerja', 'Tidak', 'Bekerja', 'Tidak', 
                  'Tidak', 'Bekerja', 'Bekerja', 'Tidak'],
    'Kelainan (Cacat)': ['Tidak', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 
                          'Tidak', 'Tidak', 'Tidak', 'Tidak'],
    'Penyakit Kronis': ['Ya', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Tidak', 
                        'Tidak', 'Ya'],
    'Predik': ['Ya', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Tidak', 
               'Ya']
})

data

,Usia,Status bangunan tempat tinggal,Pekerjaan,Kelainan (Cacat),Penyakit Kronis,Predik
0,55 Ke atas,Tidak,Tidak,Tidak,Ya,Ya
1,55 Kurang dari,Sendiri,Bekerja,Tidak,Tidak,Tidak
2,55 Ke atas,Tidak,Tidak,Tidak,Ya,Ya
3,55 Kurang dari,Tidak,Bekerja,Tidak,Tidak,Tidak
4,55 Ke atas,Tidak,Tidak,Tidak,Ya,Ya
5,55 Ke atas,Tidak,Tidak,Tidak,Tidak,Tidak
6,55 Kurang dari,Tidak,Bekerja,Tidak,Ya,Tidak
7,55 Ke atas,Tidak,Tidak,Tidak,Ya,Ya
8,55 Kurang dari,Sendiri,Bekerja,Tidak,Tidak,Tidak
9,55 Ke atas,Tidak,Tidak,Tidak,Ya,Ya
10,55 Kurang dari,Sendiri,Tidak,Tidak,Tidak,Tidak
11,55 Kurang dari,Sendiri,Bekerja,Tidak,Tidak,Tidak
12,55 Kurang dari,Sendiri,Bekerja,Tidak,Tidak,Tidak
13,55 Ke atas,Tidak,Tidak,Tidak,Ya,Ya

In [3]:
# Mengubah nilai kategorikal ke nilai numerik dengan label encoding
data_encoded = data.apply(lambda x: x.astype('category').cat.codes)

# Memisahkan atribut dan label pada data
X = data_encoded.iloc[:, :-1]
y = data_encoded.iloc[:, -1]

# Membuat objek Gaussian Naive Bayes
clf = GaussianNB()

# Melakukan training pada data
clf.fit(X, y)

# Melakukan prediksi pada data training
y_pred = clf.predict(X)

# Menghitung akurasi model
accuracy = accuracy_score(y, y_pred)
print('Akurasi: %.2f' % accuracy)

Akurasi: 1.00